version: '2'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: weather_reco_database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=weatherRecommendation@2021
    ports:
      - "57332:1433"
